services:
  frontend:
    build: .
    container_name: portfolio-sierrapablo
    restart: unless-stopped
    ports:
      - "5174:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    networks:
        - reverse-proxy

networks:
  reverse-proxy:
    external: true