services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-sierrapablo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - '4321:4321'
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
