services:
  frontend:
    build: .
    container_name: portfolio-sierrapablo
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4321:4321"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
