name: Check Prettier Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable corepack to manage pnpm
        run: corepack enable

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Run prettier check
        run: pnpm exec prettier --check . --config .prettierrc
